#
# Defines users. passwords, roles and privileges for integration test in Yamcs
#

# global parameters
passwordsHash: false     # if true, passwords hashes must use the algorithm PBKDF2WithHmacSHA1. Use the utilily hash-password.sh to hash users passords.

# user list
users:
    #   username: [password, role1, role2, ...]
    monitoring: [password, Monitoring]
    monitoring2: [password, Monitoring]
    monitoring3: [password, Monitoring]
    operator: [password, Operator]
    operator2: [password, Operator]
    supervisor: [password, Supervisor]
    spell: [spell, SPELL]

# roles and privileges
roles:
    Monitoring:
        tm_parameter_privileges: [".*"]
        tm_parameter_set_privileges: []
        tm_packet_privileges: [".*"]
        tc_privileges: []
        system_privileges: ["MayControlYProcessor", "MayGetMissionDatabase", "MayControlArchiving"]

    Operator:
        tm_parameter_privileges: [".*"]
        tm_parameter_set_privileges: []
        tm_packet_privileges: [".*"]
        tc_privileges: [".*"]
        system_privileges: ["MayControlYProcessor", "MayModifyCommandHistory", "MayControlCommandQueue", "MayCommandPayload", "MayGetMissionDatabase", "MayControlArchiving"]

    Supervisor:
        tm_parameter_privileges: [".*"]
        tm_parameter_set_privileges: [".*"]
        tm_packet_privileges: [".*"]
        tc_privileges: [".*"]
        system_privileges: ["MayControlYProcessor", "MayModifyCommandHistory", "MayControlCommandQueue", "MayCommandPayload", "MayGetMissionDatabase", "MayControlArchiving"]

    SPELL:
        tm_parameter_privileges: [".*"]
        tm_parameter_set_privileges: [".*"]
        tm_packet_privileges: [".*"]
        tc_privileges: [".*"]
        system_privileges: ["MayControlYProcessor", "MayModifyCommandHistory", "MayControlCommandQueue", "MayCommandPayload", "MayGetMissionDatabase", "MayControlArchiving"]
