#configuration for the TcpTmProvider and TcpUplinker 
# they look for properties like 
#spec:
#    tmHost: 
#    tmPort:
#    tcHost:
#    tcPort:

local:
    tmHost: 0.0.0.0
    tmPort: 14550
    tcHost: 127.0.0.1
    tcPort: 14555
