#configuration for the TcpTmProvider and TcpUplinker 
# they look for properties like 
#spec:
#    tmHost: 
#    tmPort:
#    tcHost:
#    tcPort:

local:
    tmHost: 0.0.0.0
    tmPort: 5111
    tcHost: 10.10.0.70
    tcPort: 5010
    timestampFormat: CFE_SB_TIME_32_16_SUBS 
