#configuration for the TcpTmProvider and TcpUplinker 
# they look for properties like 
#spec:
#    tmHost: 
#    tmPort:
#    tcHost:
#    tcPort:

vehicle:
    tmHost: 0.0.0.0
    tmPort: 5011
    tcHost: 127.0.0.1
    tcPort: 5010
    timestampFormat: CFE_SB_TIME_32_16_SUBS 
    OS_MAX_API_NAME: 40

ground:
    tmHost: 0.0.0.0
    tmPort: 5111
    tcHost: 127.0.0.1
    tcPort: 5013
    timestampFormat: CFE_SB_TIME_32_16_SUBS 
    OS_MAX_API_NAME: 40
