#configuration for the TcpTmProvider and TcpUplinker 
# they look for properties like 
#spec:
#    tmHost: 
#    tmPort:
#    tcHost:
#    tcPort:

local:
    tmHost: 0.0.0.0
    tmPort: 5111
#    tcHost: 127.0.0.1
    tcHost: 192.168.1.2
    tcPort: 5010
    timestampFormat: CFE_SB_TIME_32_16_SUBS 
